---
# VLAN configuration defaults
vlan_package_name: vlan

vlans: []
#  - id: 10
#    name: mgmt
#    parent_interface: eth0
#    address: "10.20.10.1/24"
#    description: "Management VLAN"
#  - id: 20
#    name: prod
#    parent_interface: eth0
#    address: "10.20.20.1/24"
#    description: "Production VLAN"
#  - id: 30
#    name: dmz
#    parent_interface: eth0
#    address: "10.20.30.1/24"
#    description: "DMZ VLAN"

vlan_use_netplan: false
vlan_use_networkd: true
